export const conceptsList: Array<Object> = [
  { name: 'Two Way Binding', id: 'twoWayBinding' },
  { name: 'Pipes', id: 'pipe' },
  { name: 'Attribute Directive', id: 'attributeDirective' },
  { name: 'Structural Directive', id: 'structuralDirective' },
  { name: 'Component Interaction', id: 'componentInteraction' },
  { name: 'Observables', id: 'observables' },
  { name: 'Template Forms', id: 'templateForms' },
  { name: 'Change Detection', id: 'changeDetection' },
  { name: 'Http Client', id: 'httpClient' },
  { name: 'Content Projection using ng-content', id: 'contentProjection' },
  { name: 'Template Variable', id: 'templateVariables' },
  { name: 'View Child', id: 'viewChild' },
  { name: 'View Children', id: 'viewChildren' },
  { name: 'Interpolation vs innerHTML', id: 'safeContent' },
  { name: 'Safe Navigation Operator', id: 'safeNavigationOperator' },
  { name: 'Content child', id: 'contentChild' },
  { name: 'NgFor', id: 'ngFor' },
  { name: 'Host Listener & Host Binding', id: 'hostSpecs' },
  { name: 'Reactive Forms', id: 'reactiveForms' }
]